### ISSUE TITLE
repo transfer

### ISSUE THREAD

**Issue by yumetodo** [yumetodo/TankFlanker#2]
@yabushita0312 このrepoの所有権をTransfer掛けているはずなので受け取ってください。
こんな感じのメールが行っているはずです。
![image](https://user-images.githubusercontent.com/10869046/73604422-c1cbdb00-45d3-11ea-80e6-8b193d4a8bff.png)

**Comment by Emiya-UBW-2** [comment]
今現在まで気づかずプッシュし続けていた罪をお許しください…
すいません、リンク先にて「Oops! That repository transfer has expired.」と言われました。再送をお願いしてもよろしいでしょうか？

**Comment by yumetodo** [comment]
再送しました

**Comment by Emiya-UBW-2** [comment]
出来ました、ありがとうございます

2020年2月7日(金) 0:43 yumetodo <notifications@github.com>:

**Comment by yumetodo** [comment]
いえいえ。
commitがpushされてるだけでは通知こないので私も渡せたつもりになって確認が遅れていました。
